package com.dz.coop.module.constant;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * @author panqz
 * @create 2017-06-24 下午3:16
 */

public enum ThirdPart {

    URL_COMMON(0L, 0, "URL"),

    SONG_SHU_YUE_DU(2L, 2, BookTypeEnum.TXT.getType(), "松鼠阅读"),
    JING_YUE(3L, 1, BookTypeEnum.TXT.getType(), "京阅互联"),
    CHUANG_BIE_KAI_XING(4L, 1, BookTypeEnum.TXT.getType(), "创别书城（恺兴）"),
    CHUANG_BIE_WEN_BO(5L, 1, BookTypeEnum.TXT.getType(), "创别书城（文博"),
    OU_JIA(6L, 1, BookTypeEnum.TXT.getType(), "偶家"),
    YUE_LAN_FAN_YU(7L, 1, BookTypeEnum.TXT.getType(), "悦蓝泛娱"),
    HONG_SHAN(8L, 1, BookTypeEnum.TXT.getType(), "红杉万橡"),
    QU_YUE(9L, 1, BookTypeEnum.TXT.getType(), "趣阅"),
    FENG_HUANG(10L, 1, BookTypeEnum.TXT.getType(), "天盈九州（凤凰）"),
    TA_DU(11L, 1, BookTypeEnum.TXT.getType(), "塔读文学"),
    DIAN_JIN_TANG(12L, 1, BookTypeEnum.TXT.getType(), "点金堂"),
    YI_YUAN(13L, 1, BookTypeEnum.TXT.getType(), "逸云书院"),
    THIRD_G(14L, 1, BookTypeEnum.TXT.getType(), "3G书城"),
    HEI_YAN(15L, 2, BookTypeEnum.TXT.getType(), "黑岩"),
    ZONG_HENG(16L, 2, BookTypeEnum.TXT.getType(), "纵横"),
    ZHONG_WEN_ZAI_XIAN(17L, 1, BookTypeEnum.TXT.getType(), "17k小说网"),
    MO_TIE_SHU_MENG_YUAN_CHUANG(18L, 1, BookTypeEnum.TXT.getType(), "磨铁数盟原创"),
    HANG_ZHOU_YING_XIONG(19L, 1, BookTypeEnum.TXT.getType(), "杭州樱熊"),
    YUN_YUE(20L, 1, BookTypeEnum.TXT.getType(), "云阅"),
    ZHU_LANG(21L, 2, BookTypeEnum.TXT.getType(), "逐浪"),
    XIAO_SHUO_JIA(24L, 1, BookTypeEnum.TXT.getType(), "小说家"),
    RUI_XUE_BAO_PU(25L, 1, BookTypeEnum.TXT.getType(), "瑞雪宝璞"),
    ZHI_SHANG(27L, 1, BookTypeEnum.TXT.getType(), "纸尚"),
    HAO_YUE_WEN_XUE(28L, 1, BookTypeEnum.TXT.getType(), "浩阅文学"),
    TAI_HE_KAI_XUAN(29L, 1, BookTypeEnum.TXT.getType(), "太和凯旋"),
    HUAN_FEI(30L, 1, BookTypeEnum.TXT.getType(), "幻飞文化"),
    MI_GU(31L, 1, BookTypeEnum.TXT.getType(), "咪咕数媒"),
    CAO_MU(32L, 1, BookTypeEnum.TXT.getType(), "草木乐动"),
    HENG_YAN(33L, 1, BookTypeEnum.TXT.getType(), "恒言中文网"),
    XING_K0NG(34L, 1, BookTypeEnum.TXT.getType(), "星空奇文"),
    BAO_TOU_YI_YUE(35L, 1, BookTypeEnum.TXT.getType(), "包头易阅"),
    SU_JIN(36L, 1, BookTypeEnum.TXT.getType(), "素锦"),
    ER_CENG_LOU(37L, 1, BookTypeEnum.TXT.getType(), "二层楼书院"),
    YUE_DU_XIAO_SHUO(38L, 1, BookTypeEnum.TXT.getType(), "阅读小说网"),
    HONG_SHU(40L, 1, BookTypeEnum.TXT.getType(), "红薯网 "),
    YUE_DU_FANG(41L, 1, BookTypeEnum.TXT.getType(), "悦读坊 "),
    SHU_HAI(42L, 1, BookTypeEnum.TXT.getType(), "书海小说网 "),
    ZHANG_MENG(43L, 1, BookTypeEnum.TXT.getType(), "掌盟"),
    YONG_ZHENG(44L, 1, BookTypeEnum.TXT.getType(), "永正"),
    NAN_JING_DI_PING_XIAN(46L, 1, BookTypeEnum.TXT.getType(), "南京地平线"),
    MEI_GUI(47L, 1, BookTypeEnum.TXT.getType(), "玫瑰文学网"),
    // 原名：阅书小说网
    YUE_SHU(49L, 1, BookTypeEnum.TXT.getType(), "91baby书城"),
    NAN_JING_YUE_MING(50L, 1, BookTypeEnum.TXT.getType(), "南京阅明"),
    TENG_HEN(51L, 1, BookTypeEnum.TXT.getType(), "藤痕书院"),
    QIN_SHU(52L, 1, BookTypeEnum.TXT.getType(), "勤书网"),
    DANG_DANG(53L, 2, BookTypeEnum.TXT.getType(), "当当"),
    SHI_DAI(54L, 1, BookTypeEnum.TXT.getType(), "时代中文网"),
    WANG_YI(55L, 1, BookTypeEnum.TXT.getType(), "网易"),
    FENG_QI_WU(56L, 1, BookTypeEnum.TXT.getType(), "凤栖梧"),
    ZHANG_ZHONG_WEN_XUE(57L, 2, BookTypeEnum.TXT.getType(), "掌中文学"),
    LUO_CHEN(58L, 1, BookTypeEnum.TXT.getType(), "落尘文学"),
    JING_XIANG(59L, 1, BookTypeEnum.TXT.getType(), "景像文学"),
    WANG_XING_LUN(60L, 1, BookTypeEnum.TXT.getType(), "最青春小说网"),
    TIAN_XIA_SHU_MENG(61L, 1, BookTypeEnum.TXT.getType(), "天下书盟"),
    GU_JIE_JIE(62L, 1, BookTypeEnum.TXT.getType(), "鬼姐姐"),
    ZHANG_DU_TIAN_XIA(63L, 1, BookTypeEnum.TXT.getType(), "掌读天下"),
    ZUI_QING_CHUN(64L, 2, BookTypeEnum.TXT.getType(), "最青春小说网"),
    BU_TUI_GUANG(65L, 1, BookTypeEnum.TXT.getType(), "不推广"),
    AI_YUE_DU(66L, 1, BookTypeEnum.TXT.getType(), "爱阅读"),
    FENG_QI(67L, 1, BookTypeEnum.TXT.getType(), "风起中文网"),
    HUA_YUN(68L, 1, BookTypeEnum.TXT.getType(), "华云数字"),
    XIN_LANG(69L, 1, BookTypeEnum.TXT.getType(), "新浪"),
    BO_YUE(71L, 1, BookTypeEnum.TXT.getType(), "博阅中文网"),
    HAO_SHU(72L, 1, BookTypeEnum.TXT.getType(), "365好书"),
    XIN_FENG(73L, 1, BookTypeEnum.TXT.getType(), "新蜂中文网"),
    TIAN_YUE_DU(74L, 2, BookTypeEnum.TXT.getType(), "甜悦读"),
    SHUANG_WEN(75L, 1, BookTypeEnum.TXT.getType(), "爽文小说网"),
    YAO_YAN(76L, 2, BookTypeEnum.TXT.getType(), "耀岩"),
    QING_CHUN(77L, 1, BookTypeEnum.TXT.getType(), "青春说小说网"),
    YUE_LAN(78L, 1, BookTypeEnum.TXT.getType(), "阅览"),
    ZHONG_ZUO_HUA_WEN(79L, 1, BookTypeEnum.TXT.getType(), "中作华文"),
    WEN_MEI_SHI_YUE(80L, 1, BookTypeEnum.TXT.getType(), "完美十月"),
    CHANG_JIANG(81L, 2, BookTypeEnum.TXT.getType(), "长江中文网"),
    MAI_BU(85L, 1, BookTypeEnum.TXT.getType(), "迈步"),
    BU_KE_NENG_SHI_JIE(86L, 1, BookTypeEnum.TXT.getType(), "不可能的世界"),
    FEI_YANG(87L, 1, BookTypeEnum.TXT.getType(), "飞扬文学网"),
    MI_YUE(88L, 2, BookTypeEnum.TXT.getType(), "蜜阅"),
    AI_MO_YUAN(90L, 1, BookTypeEnum.TXT.getType(), "爱墨源小说网"),
    SHENG_DAN(92L, 1, BookTypeEnum.TXT.getType(), "圣诞文学网"),
    MEI_LI(93L, 1, BookTypeEnum.TXT.getType(), "魅丽文化"),
    LIGN_DU(94L, 1, BookTypeEnum.TXT.getType(), "零度小说"),
    LING_YUE(96L, 1, BookTypeEnum.TXT.getType(), "灵阅文学网"),
    FENG_XING(97L, 1, BookTypeEnum.TXT.getType(), "风行"),
    YOU_YUE(98L, 2, BookTypeEnum.TXT.getType(), "优阅中文网"),
    QING_GUO(99L, 1, BookTypeEnum.TXT.getType(), "青果阅读"),
    NINTEEN_LOU(100L, 1, BookTypeEnum.TXT.getType(), "19楼"),
    HAI_YUE_WANG(101L, 2, BookTypeEnum.TXT.getType(), "海悦网"),
    DA_YU(102L, 1, BookTypeEnum.TXT.getType(), "大鱼"),
    SHU_CONG(103L, 2, BookTypeEnum.TXT.getType(), "书丛"),
    HUAN_YUE_SHI_DAI(104L, 2, BookTypeEnum.TXT.getType(), "欢悦时代"),
    YUE_WEN_XUAN(105L, 1, BookTypeEnum.TXT.getType(), "悦文轩"),
    SHENG_SHI(106L, 2, BookTypeEnum.TXT.getType(), "盛世阅读网"),
    GU_YUE_DU(107L, 1, BookTypeEnum.TXT.getType(), "古阅读"),
    JIU_YU(108L, 2, BookTypeEnum.TXT.getType(), "九域文学网"),
    CHUANG_KU(109L, 2, BookTypeEnum.TXT.getType(), "创酷中文网"),
    YUN_QUE(110L, 2, BookTypeEnum.TXT.getType(), "云雀书院"),
    MO_SHANG_XIANG_FANG(111L, 1, BookTypeEnum.TXT.getType(), "陌上香坊"),
    HUA_CE(112L, 1, BookTypeEnum.TXT.getType(), "华策文学网"),
    WAN_ZHONG(113L, 1, BookTypeEnum.TXT.getType(), "万众中文网"),
    WU_TONG(114L, 1, BookTypeEnum.TXT.getType(), "梧桐中文网"),
    JING_SE(115L, 1, BookTypeEnum.TXT.getType(), "锦瑟文学"),
    TANG_YUAN(116L, 1, BookTypeEnum.TXT.getType(), "汤圆创作"),
    YAO_CHI(117L, 1, BookTypeEnum.TXT.getType(), "瑶池文化"),
    QING_WEN(118L, 2, BookTypeEnum.TXT.getType(), "轻文"),
    LAO_HU_FA_WEI_XIAO_SHUO_WANG(119L, 1, BookTypeEnum.TXT.getType(), "老虎发威小说网"),
    YUE_TING(120L, 2, BookTypeEnum.TXT.getType(), "阅庭书院"),
    FANG_XING(121L, 2, BookTypeEnum.TXT.getType(), "繁星中文网"),
    DIAN_ZHONG_CI_YUAN(122L, 2, BookTypeEnum.TXT.getType(), "点众次元"),
    LIAN_XIAO_SHUO(123L, 1, BookTypeEnum.TXT.getType(), "恋小说"),
    PIN_YUE(124L, 1, BookTypeEnum.TXT.getType(), "品阅文学"),
    HAI_MA_QING_FAN(125L, 1, BookTypeEnum.TXT.getType(), "海马轻帆"),
    CA_HUO(126L, 2, BookTypeEnum.TXT.getType(), "擦火文学"),
    XIA_MEN_AI_YUE(127L, 2, BookTypeEnum.TXT.getType(), "厦门爱阅"),
    SHU_JIANG_WEN_XUE(130L, 2, BookTypeEnum.TXT.getType(), "书匠文学"),
    SHU_CHU(131L, 2, BookTypeEnum.TXT.getType(), "书橱小说"),
    XUAN_YU(132L, 1, BookTypeEnum.TXT.getType(), "玄娱中文网"),
    TIAN_YI(133L, 2, BookTypeEnum.TXT.getType(), "天翼阅读"),
    ZUI_TANG(134L, 1, BookTypeEnum.TXT.getType(), "醉唐中文网"),
    MIAN_HUA(135L, 1, BookTypeEnum.TXT.getType(), "棉花文学"),
    HAN_WU(136L, 1, BookTypeEnum.TXT.getType(), "寒武纪年"),
    SI_YUE_TIAN(137L, 2, BookTypeEnum.TXT.getType(), "四月天"),
    SHI_YIN(138L, 1, BookTypeEnum.TXT.getType(), "十音文学"),
    QI_RE(139L, 2, BookTypeEnum.TXT.getType(), "奇热小说"),
    QIANG_WEI(140L, 2, BookTypeEnum.TXT.getType(), "蔷薇书院（广州）"),
    DOU_DU(141L, 1, BookTypeEnum.TXT.getType(), "豆读"),
    YUE_XIN(142L, 1, BookTypeEnum.TXT.getType(), "阅心文化"),
    LONG_YUE_DU(143L, 1, BookTypeEnum.TXT.getType(), "龙阅读"),
    YUE_HAO_WAN(144L, 2, BookTypeEnum.TXT.getType(), "阅好玩"),
    YAN_BEI_TANG(145L, 1, BookTypeEnum.TXT.getType(), "雁北堂"),
    YUE_YOU(147L, 2, BookTypeEnum.TXT.getType(), "阅友"),
    JIU_KU(148L, 2, BookTypeEnum.TXT.getType(), "九库"),
    WAN_DU_XIAO_SHUO(149L, 1, BookTypeEnum.TXT.getType(), "万读小说"),
    AI_DU_WEN_XUE(150L, 1, BookTypeEnum.TXT.getType(), "爱读文学"),
    TIE_XUE(151L, 2, BookTypeEnum.TXT.getType(), "铁血"),
    DA_SHENG_ZHONG_WEN(152L, 1, BookTypeEnum.TXT.getType(), "大圣中文网"),
    HONG_SHU_GUAN(153L, 1, BookTypeEnum.TXT.getType(), "红书馆"),
    SHANG_PIN_WEN_XUE(155L, 1, BookTypeEnum.TXT.getType(), "上品文学网"),
    XING_KONG_WEN_XUE(156L, 1, BookTypeEnum.TXT.getType(), "星空文学网"),
    HONG_SHU_HUI(157L, 1, BookTypeEnum.TXT.getType(), "红书汇"),
    HONG_GUO(158L, 2, BookTypeEnum.TXT.getType(), "红果阅读"),
    MU_YUN_SHU_YUAN(159L, 1, BookTypeEnum.TXT.getType(), "牧云书院"),
    JING_LUN(160L, 1, BookTypeEnum.TXT.getType(), "经纶文学网"),
    MIAO_YUE_DU(161L, 1, BookTypeEnum.TXT.getType(), "喵阅读"),
    YANG_GUANG_YUE_DU(162L, 1, BookTypeEnum.TXT.getType(), "阳光阅读"),
    LE_TU(163L, 1, BookTypeEnum.TXT.getType(), "乐途"),
    KU_DU(164L, 1, BookTypeEnum.TXT.getType(), "酷读"),
    RI_YUE_ZHONG_WEN(165L, 1, BookTypeEnum.TXT.getType(), "日月中文网"),
    XIN_HUA_YUE_DU(166L, 1, BookTypeEnum.TXT.getType(), "新华阅读"),
    CHENG_GUA(167L, 1, BookTypeEnum.TXT.getType(), "橙瓜"),
    JU_MAO_WEN_XUE(168L, 1, BookTypeEnum.TXT.getType(), "巨猫文学"),
    YU_MAO_KAN_SHU(169L, 1, BookTypeEnum.TXT.getType(), "愚猫看书"),
    LING_YOU(170L, 1, BookTypeEnum.TXT.getType(), "灵游"),
    SHANG_YUE(171L, 1, BookTypeEnum.TXT.getType(), "尚阅"),
    JIU_HE(172L, 1, BookTypeEnum.TXT.getType(), "久和中文网"),
    MIAO_YUE(173L, 1, BookTypeEnum.TXT.getType(), "妙阅"),
    XIN_HUA_KU_DU(174L, 1, BookTypeEnum.TXT.getType(), "新华酷读文化"),
    ZHNAG_YUE(175L, 2, BookTypeEnum.TXT.getType(), "掌阅科技"),
    QI_YUE_SHU_CHENG(176L, 1, BookTypeEnum.TXT.getType(), "柒月书城"),
    YAN_XI_SHU_YUAN(179L, 1, BookTypeEnum.TXT.getType(), "言蹊书院"),
    SI_XI_WEN_XUE(180L, 1, BookTypeEnum.TXT.getType(), "四喜文学"),
    CHUANG_CE(181L, 1, BookTypeEnum.TXT.getType(), "创策"),
    TIAN_YA_WEN_XUE(182L, 1, BookTypeEnum.TXT.getType(), "天涯文学"),
    TIAN_YUE(184L, 2, BookTypeEnum.TXT.getType(), "天阅"),
    PIN_QU(185L, 2, BookTypeEnum.TXT.getType(), "品趣"),
    QING_YUE_DU(186L, 1, BookTypeEnum.TXT.getType(), "轻阅读"),
    FENG_MING_XUAN(187L, 1, BookTypeEnum.TXT.getType(), "凤鸣轩"),
    RE_DIAN(188L, 2, BookTypeEnum.TXT.getType(), "热点"),
    BAI_HEI_BAI(189L, 1, BookTypeEnum.TXT.getType(), "白黑白"),
    JING_YU(190L, 2, BookTypeEnum.TXT.getType(), "鲸鱼阅读"),
    WEI_QIAO(191L, 1, BookTypeEnum.TXT.getType(), "唯乔"),
    HENG_WEN_SHI_JI(192L, 1, BookTypeEnum.TXT.getType(), "桓文世纪"),
    QI_JING(194L, 2, BookTypeEnum.TXT.getType(), "骑鲸文化"),
    HUO_XING(195L, 1, BookTypeEnum.TXT.getType(), "火星小说"),
    SHA_YU_ZHONG_WEN(197L, 2, BookTypeEnum.TXT.getType(), "傻鱼中文网"),
    SHI_KONG_WEN_HUA(199L, 1, BookTypeEnum.TXT.getType(), "时空文化"),
    JING_ZHI_WEN_XUE(200L, 1, BookTypeEnum.TXT.getType(), "经致文学"),
    ZHI_XIN_YUE_DU(202L, 1, BookTypeEnum.TXT.getType(), "知心阅读"),
    HONG_HUA(203L, 2, BookTypeEnum.TXT.getType(), "小红花阅读"),
    XIONG_MAO(204L, 1, BookTypeEnum.TXT.getType(), "熊猫阅读"),
    KU_JIANG(205L, 1, BookTypeEnum.TXT.getType(), "酷匠"),
    CHUN_TIAN(206L, 1, BookTypeEnum.TXT.getType(), "春田小说"),
    XIONG_MAO_DUAN_PIAN(208L, 1, BookTypeEnum.TXT.getType(), "愚猫短篇"),
    XI_MA_LA_YA(210L, 1, BookTypeEnum.TXT.getType(), "喜马拉雅"),
    LONG_MAO_YUE_DU(212L, 1, BookTypeEnum.TXT.getType(), "龙猫阅读"),
    XIANG_YUE(213L, 2, BookTypeEnum.TXT.getType(), "享阅"),
    AI_ZUO_PIN(214L, 1, BookTypeEnum.TXT.getType(), "爱作品"),
    GONG_ZHU_SHU_CHENG(215L, 2, BookTypeEnum.TXT.getType(), "公主书城"),
    WU_LI_WEN_HUA(216L, 1, BookTypeEnum.TXT.getType(), "吾里文化"),
    WEN_DU_SHU_CHENG(217L, 1, BookTypeEnum.TXT.getType(), "温度书城"),
    BO_WEN(218L, 1, BookTypeEnum.TXT.getType(), "博闻"),
    HUO_SHEN(219L, 1, BookTypeEnum.TXT.getType(), "火神文学"),
    CHAO_YUE_WEN_HUA(220L, 1, BookTypeEnum.TXT.getType(), "超阅文化"),
    YU_SHU(221L, 1, BookTypeEnum.TXT.getType(), "羽书"),
    XUAN_TIAN_WEN_XUE(222L, 2, BookTypeEnum.TXT.getType(), "泫天文学"),
    XIAO_SHUO_KONG(223L, 2, BookTypeEnum.TXT.getType(), "小说控"),
    FEN_ZI_ZHI_SHI(224L, 1, BookTypeEnum.TXT.getType(), "分子知视"),
    FU_TIAN(225L, 2, BookTypeEnum.TXT.getType(), "伏天"),
    LIAN_ZHONG_WEN_XUE(226L, 1, BookTypeEnum.TXT.getType(), "连众文学"),
    XING_HE(227L, 1, BookTypeEnum.TXT.getType(), "星河"),
    ZHANG_ZHONG_YUN(228L, 2, BookTypeEnum.TXT.getType(), "掌中云"),
    BEI_JING_ZHANG_YUE(229L, 2, BookTypeEnum.TXT.getType(), "北京掌阅"),
    DING_TIAN(230L, 2, BookTypeEnum.TXT.getType(), "鼎甜文化"),
    WANG_YAO_ZU(232L, 2, BookTypeEnum.TXT.getType(), "王瑶组"),
    YOU_HU_WEN_HUA(233L, 2, BookTypeEnum.TXT.getType(), "有狐文化"),
    AI_DIAN(234L, 2, BookTypeEnum.TXT.getType(), "爱点文学"),
    AI_QI_YI(235L, 2, BookTypeEnum.TXT.getType(), "爱奇艺"),
    DONG_YUE_DU(236L, 1, BookTypeEnum.TXT.getType(), "动阅读"),
    BAN_KE_WEN_HUA(237L, 1, BookTypeEnum.TXT.getType(), "半刻文化"),
    HUO_YAN_KAN_SHU(239L, 1, BookTypeEnum.TXT.getType(), "火眼看书"),
    YU_YUE_KAN_SHU(240L, 1, BookTypeEnum.TXT.getType(), "娱阅看书"),
    AI_YUE(241L, 2, BookTypeEnum.TXT.getType(), "艾月"),
    QING_JIAO_YUE_DU(242L, 1, BookTypeEnum.TXT.getType(), "青椒阅读"),
    YOU_MI_WEN_XUE(243L, 1, BookTypeEnum.TXT.getType(), "柚米文学"),
    QING_TUN_YUE_DU(244L, 2, BookTypeEnum.TXT.getType(), "青豚阅读"),
    BAI_DING_XIAO_SHUO(245L, 1, BookTypeEnum.TXT.getType(), "白丁小说"),
    HAO_YUE(246L, 1, BookTypeEnum.TXT.getType(), "好阅"),
    XIN_YUE(247L, 1, BookTypeEnum.TXT.getType(), "欣阅"),
    QING_MAN_WEN_HUA(248L, 1, BookTypeEnum.TXT.getType(), "轻漫文化"),
    TAO_LE_WEN_XUE(249L, 1, BookTypeEnum.TXT.getType(), "桃乐文学"),
    YUE_XIA(250L, 1, BookTypeEnum.TXT.getType(), "阅下"),
    LING_HUAN_WEN_HUA(251L, 2, BookTypeEnum.TXT.getType(), "凌欢文化"),
    LIAN_YUE(253L, 1, BookTypeEnum.TXT.getType(), "联阅"),
    SHUANG_XI_WEN_XUE(254L, 1, BookTypeEnum.TXT.getType(), "双溪文学"),
    HUA_GE(255L, 1, BookTypeEnum.TXT.getType(), "花阁"),
    ZHANG_WEN(256L, 2, BookTypeEnum.TXT.getType(), "掌文"),
    AN_MA(257L, 1, BookTypeEnum.TXT.getType(), "安马"),
    MU_WEN_YE_DU(258L, 1, BookTypeEnum.TXT.getType(), "牧文野读"),
    FU_ZHOU_ZHANG_ZHONG_YUN(259L, 2, BookTypeEnum.TXT.getType(), "福州掌中云"),
    HAI_YUE(261L, 1, BookTypeEnum.TXT.getType(), "海阅"),
    FENG_HUAN(262L, 1, BookTypeEnum.TXT.getType(), "风寰"),
    DIAN_YUE(263L, 1, BookTypeEnum.TXT.getType(), "点阅"),
    JIU_MI(264L, 1, BookTypeEnum.TXT.getType(), "啾咪"),
    CHAO_SHANG_YUE(265L, 1, BookTypeEnum.TXT.getType(), "潮上月"),
    ZUI_AI_YUAN_CHUANG_WANG(266L, 1, BookTypeEnum.TXT.getType(), "最爱原创网"),
    ZHI_JIAN_YUE_DU(267L, 1, BookTypeEnum.TXT.getType(), "指尖阅读"),
    SONG_SHU_JING_PIN(268L, 2, BookTypeEnum.TXT.getType(), "松鼠精品"),
    YU_SHU_FANG(269L, 1, BookTypeEnum.TXT.getType(), "御书房"),
    BAN_QUAN_MAO(270L, 1, BookTypeEnum.TXT.getType(), "版权猫"),
    BAI_HU_YUE_DU(271L, 1, BookTypeEnum.TXT.getType(), "白狐阅读"),
    YOU_LE_ZHONG_WEN_WANG(272L, 2, BookTypeEnum.TXT.getType(), "有乐中文网"),
    HUA_HUA_ZHONG_WEN_WANG(273L, 1, BookTypeEnum.TXT.getType(), "花花中文网"),
    BI_KAN(274L, 1, BookTypeEnum.TXT.getType(), "必看"),
    HAI_CAO_ZHONG_WEN_WANG(275L, 1, BookTypeEnum.TXT.getType(), "海草中文网"),
    WANG_YOU_SHU_CHENG(276L, 1, BookTypeEnum.TXT.getType(), "忘忧书城"),
    CHANG_SHA_JIU_YUE(277L, 1, BookTypeEnum.TXT.getType(), "长沙久阅"),
    SHI_ER_YUE_DU(278L, 1, BookTypeEnum.TXT.getType(), "十二阅读"),
    JU_DIAN_WEN_XUE(279L, 2, BookTypeEnum.TXT.getType(), "据点文学"),
    QI_MAO_ZHONG_WEN_WANG(280L, 1, BookTypeEnum.TXT.getType(), "七猫中文网"),
    HAI_GE_WEN_HUA(281L, 1, BookTypeEnum.TXT.getType(), "海阁文化"),
    DIAN_ZHONG_JING_PIN(282L, 2, BookTypeEnum.TXT.getType(), "点众精品"),
    JIU_YUE_WEN_HUA(283L, 1, BookTypeEnum.TXT.getType(), "九阅文化"),
    MU_ZHI_YUE_DU(284L, 1, BookTypeEnum.TXT.getType(), "拇指阅读"),
    WAN_SHU_WEN_XUE_WANG(285L, 1, BookTypeEnum.TXT.getType(), "绾书文学网"),
    YING_HUO_XIAO_SHUO(286L, 1, BookTypeEnum.TXT.getType(), "萤火小说"),
    LIAN_CHENG_DU_SHU(287L, 1, BookTypeEnum.TXT.getType(), "连城读书"),
    TING_CHAO_GE(288L, 1, BookTypeEnum.TXT.getType(), "听潮阁"),
    MU_BEN_SHUI_YUAN(289L, 1, BookTypeEnum.TXT.getType(), "木本水源"),
    LAN_YUE_DU(290L, 1, BookTypeEnum.TXT.getType(), "蓝阅读"),
    MAN_YU_KE_JI(291L, 1, BookTypeEnum.TXT.getType(), "漫娱科技"),
    YUAN_CHUAN_SHU_DIAN(292L, 2, BookTypeEnum.TXT.getType(), "原创书殿"),
    CHENG_DU_YUE_TING(293L, 1, BookTypeEnum.TXT.getType(), "成都悦听"),
    QING_CAO_WEN_HUA(294L, 2, BookTypeEnum.TXT.getType(), "青草文化"),
    BAN_KE_ZHONG_WEN_WANG(295L, 2, BookTypeEnum.TXT.getType(), "半刻中文网"),
    XIAO_LIAN_YUE_DU(296L, 1, BookTypeEnum.TXT.getType(), "晓恋悦读"),
    YOU_SHU_QIAN_JUAN(297L, 2, BookTypeEnum.TXT.getType(), "有书千卷"),
    SONG_SHU_YUAN_CHUANG(298L, 2, BookTypeEnum.TXT.getType(), "松鼠原创"),
    SI_WEI_WEN_XUE(299L, 1, BookTypeEnum.TXT.getType(), "四维文学"),
    QIAN_MA_ZHONG_WEN_WANG(300L, 1, BookTypeEnum.TXT.getType(), "千马中文网"),
    LIAN_ZAI_YUE_DU(301L, 1, BookTypeEnum.TXT.getType(), "连载阅读"),
    LAN_YUE_ZHONG_WEN_WANG(302L, 1, BookTypeEnum.TXT.getType(), "揽月中文网"),
    YI_YI_YUE_DU(303L, 1, BookTypeEnum.TXT.getType(), "一一阅读"),
    YI_SOU(304L, 1, BookTypeEnum.TXT.getType(), "宜搜"),
    XI_CHENG_WEN_HUA(305L, 1, BookTypeEnum.TXT.getType(), "西橙文化"),
    JI_LIN_XUN_MA_WANG_LUO(306L, 1, BookTypeEnum.TXT.getType(), "吉林讯码网络"),
    BA_NIAN_WANG_LUO(307L, 1, BookTypeEnum.TXT.getType(), "八年网络"),
    JIN_YUE(308L, 1, BookTypeEnum.TXT.getType(), "锦阅"),
    HAI_TUN_YUE_DU(309L, 1, BookTypeEnum.TXT.getType(), "海豚阅读"),
    XING_YAN_WEN_HUA(310L, 1, BookTypeEnum.TXT.getType(), "星雁文化"),
    DA_YU_KUAI_DU(311L, 1, BookTypeEnum.TXT.getType(), "大鱼快读"),
    ZI_WEI_WEN_XUE(312L, 1, BookTypeEnum.TXT.getType(), "紫薇文学"),
    ZHONG_DU(313L, 1, BookTypeEnum.TXT.getType(), "众读"),
    FAN_TANG_XIAO_SHUO(314L, 1, BookTypeEnum.TXT.getType(), "翻糖小说"),
    MAN_BU_WEN_XUE(315L, 1, BookTypeEnum.TXT.getType(), "漫步文学"),
    YOU_BAN_XIAO_SHUO(316L, 1, BookTypeEnum.TXT.getType(), "有伴小说"),
    SHU_XIANG_SI_HAI(317L, 2, BookTypeEnum.TXT.getType(), "书香四海"),
    YUN_XING_ZHONG_WEN_WANG(318L, 1, BookTypeEnum.TXT.getType(), "云行中文网"),
    YOU_HE(319L, 1, BookTypeEnum.TXT.getType(), "友和"),
    JIU_CHUANG_WEN_XUE(320L, 2, BookTypeEnum.TXT.getType(), "九创文学"),
    XUAN_HUANG_WEN_HUA(321L, 1, BookTypeEnum.TXT.getType(), "煊煌文化"),
    DOU_FU_YUE_DU(322L, 1, BookTypeEnum.TXT.getType(), "豆腐阅读"),
    JIU_ZHOU_XIAO_SHUO(323L, 1, BookTypeEnum.TXT.getType(), "九州小说"),
    LAN_ZE_SHU_YUAN(324L, 1, BookTypeEnum.TXT.getType(), "兰泽书院"),
    HUA_XI_XIAO_SHUO(325L, 1, BookTypeEnum.TXT.getType(), "花溪小说"),
    HONG_SHU_WANG_HAI_WAI(326L, 1, BookTypeEnum.TXT.getType(), "红薯网（海外）"),
    HONG_XIANG_WEN_XUE(327L, 1, BookTypeEnum.TXT.getType(), "红象文学"),
    BAI_MA_SHI_GUANG_ZHONG_WEN_WANG(328L, 1, BookTypeEnum.TXT.getType(), "白马时光中文网"),
    SI_JI_WEN_XUE(329L, 1, BookTypeEnum.TXT.getType(), "四季文学"),
    HONG_SHU_WANG_FEN_XIAO(330L, 1, BookTypeEnum.TXT.getType(), "红薯网（分销）"),
    XIANG_GUA_YUE_DU(331L, 1, BookTypeEnum.TXT.getType(), "香瓜阅读"),
    MI_DU_WEN_XUE(332L, 2, BookTypeEnum.TXT.getType(), "米读文学"),
    ZHU_MENG_WEN_XUE(333L, 1, BookTypeEnum.TXT.getType(), "筑梦文学"),
    DA_MAI_ZHONG_JIN(334L, 1, BookTypeEnum.TXT.getType(), "大麦中金"),
    SU_GENG_XIAO_SHUO(335L, 1, BookTypeEnum.TXT.getType(), "速更小说"),
    GUANG_ZHOU_TIE_DU(336L, 1, BookTypeEnum.TXT.getType(), "广州铁读"),
    KAN_DIAN_WEN_HUA(337L, 1, BookTypeEnum.TXT.getType(), "看点文化"),
    LI_ZHI_YUE_DU(338L, 1, BookTypeEnum.TXT.getType(), "荔枝阅读"),
    FEI_RAN_CHENG_ZHANG(340L, 1, BookTypeEnum.TXT.getType(), "斐然成章"),
    ZHI_ZI_HUAN(341L, 1, BookTypeEnum.TXT.getType(), "栀子欢"),
    NUAN_YUE_XIAO_SHUO_WANG(342L, 1, BookTypeEnum.TXT.getType(), "暖阅小说网"),
    TONG_NIAN_MU_MIAN(343L, 1, BookTypeEnum.TXT.getType(), "桐年牧棉"),
    ZI_YUN_SHU_CHENG(344L, 1, BookTypeEnum.TXT.getType(), "紫韵书城"),
    HUO_DIAN_WEN_HUA(345L, 1, BookTypeEnum.TXT.getType(), "火点文化"),
    ZHI_HUI_CHUANG_RONG(346L, 1, BookTypeEnum.TXT.getType(), "智汇创融"),
    SONG_JIA_WEN_HUA(348L, 1, BookTypeEnum.TXT.getType(), "嵩嘉文化"),
    SHANG_HAI_TUO_CHANG(349L, 1, BookTypeEnum.TXT.getType(), "上海拓畅"),
    BI_SHANG(350L, 2, BookTypeEnum.TXT.getType(), "笔尚"),
    XIN_SHENG_DAI_WEN_XUE_WANG(351L, 1, BookTypeEnum.TXT.getType(), "新生代文学网"),
    JI_YUAN_WEN_HUA(352L, 1, BookTypeEnum.TXT.getType(), "寄远文化"),
    YAN_RU_YU_XIAO_SHUO(353L, 2, BookTypeEnum.TXT.getType(), "颜如玉小说"),
    YING_XUE_DU_SHU(354L, 2, BookTypeEnum.TXT.getType(), "映雪读书"),
    BI_MO_SHU_XIANG(355L, 2, BookTypeEnum.TXT.getType(), "笔墨书香"),
    ZHONG_HENG_ZHONG_WEN_WANG(356L, 2, BookTypeEnum.TXT.getType(), "纵横中文网"),
    KE_YI(357L, 2, BookTypeEnum.TXT.getType(), "苛苡"),
    HANG_ZHOU_YAO_CHI(358L, 1, BookTypeEnum.TXT.getType(), "杭州瑶池"),
    CHENG_GUA_YUE_DU(359L, 1, BookTypeEnum.TXT.getType(), "橙瓜阅读"),
    ZHONG_WEN_WAN_WEI(360L, 1, BookTypeEnum.TXT.getType(), "中文万维"),
    SEVEN_LOU_ZHONG_WEN_WANG(361L, 1, BookTypeEnum.TXT.getType(), "7楼中文网"),
    WEI_YUE_SHU_MENG(362L, 1, BookTypeEnum.TXT.getType(), "微阅数盟"),
    NIU_JIAO_KE_JI(363L, 1, BookTypeEnum.TXT.getType(), "牛角科技"),
    SHU_HAI_MAI_DUAN(364L, 1, BookTypeEnum.TXT.getType(), "书海买断"),
    GU_YUN_WEN_XUE(365L, 1, BookTypeEnum.TXT.getType(), "谷韵文学"),
    HONG_RU_WEN_HUA(366L, 1, BookTypeEnum.TXT.getType(), "弘儒文化"),
    HANG_ZHOU_QU_YUE(367L, 1, BookTypeEnum.TXT.getType(), "杭州趣阅"),
    QI_YUN_WEN_XUE(368L, 1, BookTypeEnum.TXT.getType(), "启云文学"),
    FENG_XING_ZHONG_WEN_WANG(369L, 1, BookTypeEnum.TXT.getType(), "疯行中文网"),
    QING_KONG_ZHI_LAN(371L, 1, BookTypeEnum.TXT.getType(), "青空之蓝"),
    CHENG_DU_QU_DU(372L, 1, BookTypeEnum.TXT.getType(), "成都趣读"),
    ZHI_YUE_WEN_HUA(373L, 1, BookTypeEnum.TXT.getType(), "智阅文化"),
    YOU_LE_FEN_CHENG(374L, 1, BookTypeEnum.TXT.getType(), "有乐分成"),
    TANG_GUA_XIAO_SHUO(375L, 1, BookTypeEnum.TXT.getType(), "糖瓜小说"),
    YUAN_QI_MENG(376L, 1, BookTypeEnum.TXT.getType(), "元气萌"),
    QIANG_HUA_WEN_XUE(377L, 1, BookTypeEnum.TXT.getType(), "枪花文学"),
    SI_XI(378L, 1, BookTypeEnum.TXT.getType(), "四喜"),
    FEN_WU_WEN_XUE(379L, 1, BookTypeEnum.TXT.getType(), "粉雾文学"),
    FENG_DU(380L, 2, BookTypeEnum.TXT.getType(), "疯读"),
    BEI_DOU(381L, 1, BookTypeEnum.TXT.getType(), "北斗"),
    XIN_YU_MENG(382L, 1, BookTypeEnum.TXT.getType(), "心语梦"),
    XIN_YUE_WEN_HUA(383L, 1, BookTypeEnum.TXT.getType(), "薪阅文化"),
    HUA_MEI_REN_XIAO_SHUO(384L, 1, BookTypeEnum.TXT.getType(), "画美人小说"),
    FEI_YUE_XIAO_SHUO(385L, 1, BookTypeEnum.TXT.getType(), "飞阅小说"),
    BI_MO(386L, 2, BookTypeEnum.TXT.getType(), "笔墨"),
    BO_YU_YUE_DU(387L, 1, BookTypeEnum.TXT.getType(), "博宇阅读"),
    LAN_MAO_YUE_DU_WANG(388L, 1, BookTypeEnum.TXT.getType(), "懒猫阅读网"),
    ZHI_XIN(389L, 1, BookTypeEnum.TXT.getType(), "知心"),
    JING_ZHI_WEN_XUE_XIN_ZHAN(391L, 1, BookTypeEnum.TXT.getType(), "经致文学新站"),
    FEI_YU(392L, 1, BookTypeEnum.TXT.getType(), "飞鱼"),
    BI_XIA_SHENG_HUA(393L, 2, BookTypeEnum.TXT.getType(), "笔下生花"),
    XIANG_SEN_WEN_HUA(394L, 1, BookTypeEnum.TXT.getType(), "象森文化"),
    YI_SHU(396L, 1, BookTypeEnum.TXT.getType(), "意书"),
    ZHONG_YI(397L, 1, BookTypeEnum.TXT.getType(), "中意"),
    TIAN_DU_WEN_HUA(398L, 2, BookTypeEnum.TXT.getType(), "天读文化"),
    LI_WAN(399L, 1, BookTypeEnum.TXT.getType(), "立玩"),
    LU_YUE_DU(400L, 1, BookTypeEnum.TXT.getType(), "鹿阅读"),
    YUAN_YUAN_GUN_GUN(401L, 1, BookTypeEnum.TXT.getType(), "源源滚滚"),
    MEI_LI_QI_PAO(402L, 1, BookTypeEnum.TXT.getType(), "美丽气泡"),
    MO_KE(406L, 1, BookTypeEnum.TXT.getType(), "墨客"),
    WEI_WAN_KE_JI(407L, 1, BookTypeEnum.TXT.getType(), "未晚科技"),
    HAO_YUE2(408L, 1, BookTypeEnum.TXT.getType(), "豪阅"),
    QU_WEN(409L, 1, BookTypeEnum.TXT.getType(), "趣文"),
    YOU_SHU(410L, 1, BookTypeEnum.TXT.getType(), "悠书"),
    LE_DU(411L, 1, BookTypeEnum.TXT.getType(), "乐读"),
    XUAN_TANG_XIAO_SHUO(412L, 1, BookTypeEnum.TXT.getType(), "炫糖小说"),
    FENG_XING_MAI_DUAN(413L, 1, BookTypeEnum.TXT.getType(), "疯行买断"),
    MO_QING(414L, 1, BookTypeEnum.TXT.getType(), "魔情"),
    BEI_JING_DIAN_YUE(415L, 1, BookTypeEnum.TXT.getType(), "北京点阅"),
    YI_DU_WEN_HUA(416L, 1, BookTypeEnum.TXT.getType(), "易读文化"),
    RUO_TANG(417L, 1, BookTypeEnum.TXT.getType(), "若棠"),
    SHU_YU_WEN_XUE(418L, 1, BookTypeEnum.TXT.getType(), "书予文学"),
    CHENG_MAN_TANG(419L, 1, BookTypeEnum.TXT.getType(), "橙漫堂"),
    SAN_MIAO_YUE_DU(420L, 1, BookTypeEnum.TXT.getType(), "三喵阅读"),
    YIN_XING_WEN_XUE(421L, 1, BookTypeEnum.TXT.getType(), "银杏文学"),
    JIANG_XIN_WEN_XUE(422L, 1, BookTypeEnum.TXT.getType(), "匠心文学"),
    QING_YUN_YUE_DU(423L, 1, BookTypeEnum.TXT.getType(), "青云阅读"),
    XING_YUN_LIU_SHUI(424L, 2, BookTypeEnum.TXT.getType(), "行云流水"),
    HUI_LING_GE_WEN_HUA(425L, 1, BookTypeEnum.TXT.getType(), "绘灵阁文化"),
    FEI_YUE_DU(426L, 1, BookTypeEnum.TXT.getType(), "飞阅读"),
    WO_KE_QI_YUE_WANG_LUO(427L, 1, BookTypeEnum.TXT.getType(), "蜗壳旗阅网络"),
    MENG_MA_WEN_XUE(428L, 1, BookTypeEnum.TXT.getType(), "猛犸文学"),
    ZHONG_GUANG_YING_YIN(429L, 1, BookTypeEnum.TXT.getType(), "中广影音"),
    JI_GUANG_WEN_XUE(430L, 1, BookTypeEnum.TXT.getType(), "吉光文学"),
    QI_YUE(431L, 1, BookTypeEnum.TXT.getType(), "启阅"),
    FAN_SHU_XIAO_SHUO(432L, 1, BookTypeEnum.TXT.getType(), "番薯小说"),
    YUAN_TUAN_WEN_HUA(433L, 1, BookTypeEnum.TXT.getType(), "圆团文化"),
    BI_XIN_WEN_XUE(434L, 1, BookTypeEnum.TXT.getType(), "笔芯文学"),
    GAI_SHI_ZHONG_WEN_WANG(435L, 1, BookTypeEnum.TXT.getType(), "盖世中文网"),
    MAO_JIU_XIAO_SHUO(436L, 1, BookTypeEnum.TXT.getType(), "猫九小说"),
    YUE_KAN(437L, 1, BookTypeEnum.TXT.getType(), "阅看"),
    YAN_MENG_WEN_XUE(438L, 1, BookTypeEnum.TXT.getType(), "言梦文学"),
    SHU_ZHONG_WEN_HUA(439L, 1, BookTypeEnum.TXT.getType(), "书中文化"),
    LAO_HU_FA_WEI(440L, 1, BookTypeEnum.TXT.getType(), "老虎发威"),
    SHU_QI_XIAO_SHUO(442L, 2, BookTypeEnum.TXT.getType(), "书旗小说"),
    YUN_DING_XIAO_SHUO_WANG(443L, 1, BookTypeEnum.TXT.getType(), "云顶小说网"),
    YONG_JIU_WEN_XUE(444L, 1, BookTypeEnum.TXT.getType(), "永久文学"),
    LIU_SU_WEN_XUE(446L, 1, BookTypeEnum.TXT.getType(), "流苏文学"),
    XIU_LIN_XIAO_SHUO(447L, 1, BookTypeEnum.TXT.getType(), "秀林小说"),
    LU_SHI_JIE(448L, 1, BookTypeEnum.TXT.getType(), "鹿世界"),
    HUO_WEN_XIAO_SHUO(449L, 1, BookTypeEnum.TXT.getType(), "火文小说"),
    XI_SHUI_XIAO_SHUO(451L, 1, BookTypeEnum.TXT.getType(), "溪水小说"),
    MO_TIE(452L, 1, BookTypeEnum.TXT.getType(), "磨铁"),
    XI_YUE_XIAO_SHUO(453L, 1, BookTypeEnum.TXT.getType(), "溪阅小说"),
    GUANG_ZHOU_ZHI_XIN(455L, 1, BookTypeEnum.TXT.getType(), "广州知心"),
    WAN_CENG_ZHONG_WEN_WANG(456L, 2, BookTypeEnum.TXT.getType(), "万层中文网"),
    YING_XIU(457L, 1, BookTypeEnum.TXT.getType(), "盈袖"),
    YOU_MI_YUE_DU_WANG(458L, 1, BookTypeEnum.TXT.getType(), "有米阅读网"),
    JIU_HUAI_ZHONG_WEN_WANG(459L, 1, BookTypeEnum.TXT.getType(), "九怀中文网"),
    KE_HAI_WEN_XUE(460L, 1, BookTypeEnum.TXT.getType(), "珂海文学"),
    FAN_GUO_WEN_XUE(461L, 1, BookTypeEnum.TXT.getType(), "番果文学"),
    JI_ZHI_WEN_XUE(462L, 1, BookTypeEnum.TXT.getType(), "极致文学"),
    PING_ZHI(463L, 1, BookTypeEnum.TXT.getType(), "平治"),
    ZHONG_YUE(464L, 1, BookTypeEnum.TXT.getType(), "众阅"),
    SAN_JIE_ZHONG_WEN_WANG(465L, 1, BookTypeEnum.TXT.getType(), "三界中文网"),
    SHU_WEI_WEN_XUE(466L, 1, BookTypeEnum.TXT.getType(), "书唯文学"),
    FENG_MING_HU_YU(467L, 1, BookTypeEnum.TXT.getType(), "凤鸣互娱"),
    XING_YUE_WEN_HUA(468L, 1, BookTypeEnum.TXT.getType(), "星阅文化"),
    AN_YUE(469L, 1, BookTypeEnum.TXT.getType(), "安阅"),
    YAN_HUANG_WEN_HUA(471L, 1, BookTypeEnum.TXT.getType(), "炎煌文化"),
    XUN_DU(472L, 1, BookTypeEnum.TXT.getType(), "讯读"),
    JIANG_XI_HUAN_WEN(473L, 1, BookTypeEnum.TXT.getType(), "江西环文"),
    YIN_ZHAN_KE_JI(474L, 1, BookTypeEnum.TXT.getType(), "银展科技"),
    SHU_SHAN_YUE_YUN(475L, 1, BookTypeEnum.TXT.getType(), "书山悦云"),
    ZHE_JIANG_CHAO_YUAN_YU(476L, 1, BookTypeEnum.TXT.getType(), "浙江超元域"),
    YI_MI(477L, 1, BookTypeEnum.TXT.getType(), "依米"),
    RU_XING_KE_JI(478L, 1, BookTypeEnum.TXT.getType(), "如星科技"),
    BAI_NIAN_SHI_JUE(479L, 1, BookTypeEnum.TXT.getType(), "百年视觉"),
    MI_BO_WEN_HUA(480L, 1, BookTypeEnum.TXT.getType(), "咪波文化"),
    YOU_QIAN_WEN_HUA(20004L, 1, BookTypeEnum.TXT.getType(), "有乾文化"),
    QIAN_YI_KE_JI(20006L, 1, BookTypeEnum.TXT.getType(), "谦译科技"),
    PENG_LAI_ZHONG_WEN_WANG(20013L, 1, BookTypeEnum.TXT.getType(), "蓬莱中文网"),
    ZHONG_WEN_ZAI_XIAN_XIN_JIE_KOU(20018L, 1, BookTypeEnum.TXT.getType(), "中文在线新接口"),
    ZHANG_DU(20027L, 1, BookTypeEnum.TXT.getType(), "掌读"),
    QU_YUE_DUAN_PIAN(20031L, 1, BookTypeEnum.TXT.getType(), "趣阅短篇"),
    JIANG_NAN_SHU_CHENG(20033L, 1, BookTypeEnum.TXT.getType(), "江南书城"),
    YAO_YAO_WEN_HUA(20034L, 1, BookTypeEnum.TXT.getType(), "夭夭文化"),
    MO_YAN_KE_JI(20036L, 1, BookTypeEnum.TXT.getType(), "魔眼科技"),
    DAO_DAO_WEN_HUA(20054L, 1, BookTypeEnum.TXT.getType(), "刀刀文化"),
    FENG_YE_XIAO_SHUO(20068L, 1, BookTypeEnum.TXT.getType(), "枫叶小说"),
    JIU_ZHE_WEN_XUE(20090L, 1, BookTypeEnum.TXT.getType(), "就这文学"),
    HAI_NAN_ZHANG_YUE(20107L, 2, BookTypeEnum.TXT.getType(), "海南掌阅"),
    DIAN_ZHONG_HAI_WAI(20120L, 2, BookTypeEnum.TXT.getType(), "点众海外"),
    JIAN_SHU(20131L, 1, BookTypeEnum.TXT.getType(), "简书"),
    NAN_JING_HONG_SHU(20133L, 1, BookTypeEnum.TXT.getType(), "南京红薯"),
    BEI_JING_YU_YUE_DU(11111111L, 1, BookTypeEnum.TXT.getType(), "北京娱阅读"),
    CHUAN_MEI_CHUANG_XIANG(1010L, 2, BookTypeEnum.TXT.getType(), "传媒创项"),
    ZHONG_WEN(1055L, 2, BookTypeEnum.TXT.getType(), "中文在线"),
    BO_YI(7000L, 1, BookTypeEnum.TXT.getType(), "博易"),
    ALI_WEN_XUE(10008L, 2, BookTypeEnum.TXT.getType(), "阿里文学"),
    DOU_FU(100033L, 2, BookTypeEnum.TXT.getType(), "豆腐"),
    SHU_XIANG(100333L, 2, BookTypeEnum.TXT.getType(), "看书网-书香"),
    DAN_DING(100334L, 2, BookTypeEnum.TXT.getType(), "看书网-丹鼎"),
    JU_DIAN(100335L, 2, BookTypeEnum.TXT.getType(), "看书网-聚点"),
    BO_JI_XIN_MEI(100336L, 1, BookTypeEnum.TXT.getType(), "博集新媒"),
    SHUI_MU_SHUANG_QING(100337L, 1, BookTypeEnum.TXT.getType(), "水木双清"),
    HUA_WEN(100338L, 1, BookTypeEnum.TXT.getType(), "华文出版社"),
    SHI_DAI_HUA_WEN(100339L, 1, BookTypeEnum.TXT.getType(), "时代华文书局"),
    YIN_GU(100340L, 1, BookTypeEnum.TXT.getType(), "吟谷文化"),
    HUA_ZHE_YUAN(100341L, 1, BookTypeEnum.TXT.getType(), "华哲苑"),
    XIAO_SHUO_WANG(100342L, 1, BookTypeEnum.TXT.getType(), "6月小说网"),
    MI_HAN_SHU_YUAN(100377L, 1, BookTypeEnum.TXT.getType(), "弥汉书院"),
    MI_HAN2_SHU_YUAN(100389L, 1, BookTypeEnum.TXT.getType(), "弥翰书院"),
    JIN_RI_TOU_TIAO(100400L, 2, BookTypeEnum.TXT.getType(), "今日头条"),
    BAI_CHUAN_ZHONG_WEN_WANG(100402L, 1, BookTypeEnum.TXT.getType(), "百川中文网"),
    AI_YAO_HU_YU(7443675L, 1, BookTypeEnum.TXT.getType(), "哎呦互娱"),
    XIAO_SHUO_PIN_DAO(15178004L, 2, BookTypeEnum.TXT.getType(), "小说频道"),
    JIN_JIANG(100080665993L, 2, BookTypeEnum.TXT.getType(), "晋江"),

    // 有声读物从30000000开始编号
    NAN_JING_MENG_LU(30000000L, 2, BookTypeEnum.AUDIO.getType(), "南京萌鹿"),
    QING_TING_FM(30000001L, 2, BookTypeEnum.AUDIO.getType(), "蜻蜓FM"),
    SHA_YU_ZHONG_WEN_WANG_YOU_SHENG(30000002L, 1, BookTypeEnum.AUDIO.getType(), "傻鱼中文网（有声）"),
    ZHONG_QI_RUI_MING(30000003L, 1, BookTypeEnum.AUDIO.getType(), "中企瑞铭"),

    HUA_YUAN_LU_DUAN_PIAN(20504L, 2, BookTypeEnum.TXT.getType(), "花园鹿短篇"),

    MU_DAN_YUAN_DUAN_PIAN(20501L, 2, BookTypeEnum.TXT.getType(), "牡丹圆短篇"),
    ZHU_JIE_DUAN_PIAN(20799L, 2, BookTypeEnum.TXT.getType(), "竹节短篇"),
    ;

    private Long cpId;

    /**
     * 1：我方标准，2：对方标准
     */
    private int type;

    /**
     * 书籍类型：1.文本，2.有声读物
     */
    private int bookType;

    private String name;

    ThirdPart(Long cpId, int type, String name) {
        this.cpId = cpId;
        this.type = type;
        this.name = name;
    }

    ThirdPart(Long cpId, int type, int bookType, String name) {
        this.cpId = cpId;
        this.type = type;
        this.bookType = bookType;
        this.name = name;
    }

    public Long getCpId() {
        return cpId;
    }

    public void setCpId(Long cpId) {
        this.cpId = cpId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getBookType() {
        return bookType;
    }

    public void setBookType(int bookType) {
        this.bookType = bookType;
    }

    /**
     * 判断cp是否是我方标准，true为是
     * @param cpId
     * @return
     */
    public static boolean isThirdPartCommon(Long cpId) {
        ThirdPart[] values = ThirdPart.values();

        List<ThirdPart> collect = Arrays.stream(values)
                .filter(thirdPart -> thirdPart.getType() == 1)
                .collect(Collectors.toList());

        for (ThirdPart tp : collect) {
            if (tp.getCpId().equals(cpId)) {
                return true;
            }
        }

        return false;
    }

    public static ThirdPart[] getThirdPartOfCommon() {
        ThirdPart[] values = ThirdPart.values();
        List<ThirdPart> collect = Arrays.stream(values)
                .filter(thirdPart -> thirdPart.getType() == 1)
                .collect(Collectors.toList());
        return collect.toArray(new ThirdPart[collect.size()]);
    }

}
